[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Allow-Access-Control-Origin = "*"
    Access-Control-Allow-Headers = "Origin, Authorization, X-Requested-With, Content-Type, Accept"
    Access-Control-Allow-Methods = "POST, GET, PUT, DELETE, OPTIONS"